DROP TABLE IF EXISTS PROIZVOD;
CREATE TABLE PROIZVOD(
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    NAZIV VARCHAR(255),
    OPIS VARCHAR(255),
    CIJENA DECIMAL,
    KOLICINA NUMBER,
    BRAND_ID NUMBER
);

DROP TABLE IF EXISTS BRAND;
CREATE TABLE BRAND(
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    NAZIV VARCHAR(255)
);

DROP TABLE IF EXISTS NARUDZBA;
CREATE TABLE NARUDZBA(
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    DATUM DATE,
    UKUPNA_CIJENA_BEZ_P DECIMAL,
    UKUPNA_CIJENA_S_P DECIMAL,
    KOD_ZA_POPUST_ID NUMBER,
    NACIN_PLACANJA_ID NUMBER,
    BROJ_KARTICE VARCHAR(255),
    EMAIL VARCHAR(255),
    BROJ_MOBITELA NUMBER(255),
    ADRESA_DOSTAVE VARCHAR(255),
    NAPOMENA VARCHAR(255)
);

DROP TABLE IF EXISTS NARUDZBA_PROIZVODI;
CREATE TABLE NARUDZBA_PROIZVODI(
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    NARUDZBA_ID NUMBER,
    PROIZVOD_ID NUMBER
);

DROP TABLE IF EXISTS NACIN_PLACANJA;
CREATE TABLE NACIN_PLACANJA(
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    NAZIV VARCHAR(255)
);

DROP TABLE IF EXISTS POPUST_KODOVI;
CREATE TABLE POPUST_KODOVI(
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    KOD VARCHAR(255),
    POPUST DECIMAL,
    ISKORISTEN BOOLEAN
);

INSERT INTO BRAND (NAZIV) VALUES
    ('Nike'),
    ('Adidas'),
    ('Puma'),
    ('Reebok');

INSERT INTO POPUST_KODOVI (KOD, POPUST, ISKORISTEN) VALUES
    ('CISTA_DESETKA', 0.1, FALSE),
    ('POLA_POLA',0.5, FALSE),
    ('PROMO_KOD_5', 0.05, FALSE),
    ('PROMO_KOD_15', 0.15, FALSE),
    ('PROMO_KOD_10', 0.1, FALSE),
    ('PROMO_KOD_20', 0.2, FALSE);

INSERT INTO NACIN_PLACANJA (NAZIV) VALUES
    ('KARTIČNO'),
    ('GOTOVINSKO');

INSERT INTO PROIZVOD (NAZIV, OPIS, CIJENA, KOLICINA, BRAND_ID) VALUES
    ('Air Force 1', 'Nike tenisice', 900, 5, 1),
    ('Continental 80', 'Adidas tenisice', 800, 3, 2),
    ('Ralph Sampson', 'Puma tenisice', 750, 2, 3),
    ('Club C', 'Reebok tenisice', 700, 5, 4);


